language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t cmpak/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true cmpak/docker-react npm run test