language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t changminpak/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true changminpak/docker-react npm run test